-- Seed data from MongoDB migration
-- Runs on every startup (uses UPSERT, safe to re-run)

INSERT INTO users (name, email, password, role, created_at) VALUES ('Default Admin', 'admin@charity.com', '$2b$12$3tq.1AwIdmsiAisPbKBzbuTCJTXbv7gE0CY0zyNqC2DdzPduQFdlG', 'admin', '2026-05-25T19:22:23.882Z') ON CONFLICT (email) DO UPDATE SET password = EXCLUDED.password, name = EXCLUDED.name, role = EXCLUDED.role;
INSERT INTO users (name, email, password, role, created_at) VALUES ('Staff Test', 'staff-role-check@example.com', '$2b$10$oVWA.gJZIQP0YNiF4rRhEuWwvlKE3sb9Sb7UxEEtlyy1uN7t3XlGG', 'staff', '2026-08-02T22:09:09.136Z') ON CONFLICT (email) DO UPDATE SET password = EXCLUDED.password, name = EXCLUDED.name, role = EXCLUDED.role;
INSERT INTO news (title, content, category, image_url, created_at, updated_at) VALUES ('سەردانی فەرمی بۆ رێکخراوی تەندروستی', 'لە ڕۆژی دووشەممە، ٢٠٢٥/٠١/١٠، وەفدێکی ڕێکخراوی مرۆڤدۆستان سەردانی رێکخراوی تەندروستی جیهانی کرد بۆ باسکردنی پرۆژەکانی هاوبەش', 'KurdishVisitors', NULL, '2026-05-25T19:28:36.566Z', '2026-05-25T19:28:36.593Z') ON CONFLICT DO NOTHING;
INSERT INTO news (title, content, category, image_url, created_at, updated_at) VALUES ('وەرگرتنی سوپاس و پێزانین', 'رێکخراوەکەمان بەڕێزنامەی سوپاسی لە لایەن وەزارەتی تەندروستیەوە ڕێزی لێ نرا بۆ کارە مرۆڤدۆستییەکانمان', 'KurdishCertificate', NULL, '2026-05-25T19:28:36.666Z', '2026-05-25T19:28:36.668Z') ON CONFLICT DO NOTHING;
INSERT INTO news (title, content, category, image_url, created_at, updated_at) VALUES ('Official Visit to Health Ministry', 'Our organization conducted an official visit to the Ministry of Health to discuss ongoing projects and future collaborations.', 'SardaniFrami', NULL, '2026-05-25T19:28:36.675Z', '2026-05-25T19:28:36.677Z') ON CONFLICT DO NOTHING;
INSERT INTO projects (title, description, category, status, image_url, location, created_at, updated_at) VALUES ('دابینکردنی دەرمانی پێویست بۆ نەخۆشخانەکان', 'لە ڕۆژی دووشەممە، ٢٠٢٥/٠١/١٠، رێکخراوی مرۆڤدۆستان دەرمانی پێویستی دابین کرد بۆ نەخۆشخانە و بنکەی تەندروستی لە شاری هەولێر', NULL, 'completed', NULL, NULL, '2026-05-25T19:28:36.690Z', '2026-05-25T19:28:36.692Z') ON CONFLICT DO NOTHING;
INSERT INTO projects (title, description, category, status, image_url, location, created_at, updated_at) VALUES ('دابەشکردنی سەبەتەی خۆراک', 'دابەشکردنی سەبەتەی خۆراک و هێلکە بۆ خاوەنپێدایوستی تایبەت لە پارێزگای دهۆک', NULL, 'completed', NULL, NULL, '2026-05-25T19:28:36.698Z', '2026-05-25T19:28:36.700Z') ON CONFLICT DO NOTHING;
INSERT INTO projects (title, description, category, status, image_url, location, created_at, updated_at) VALUES ('نۆژەنکردنەوەی قوتابخانە', 'نۆژەنکردنەوەی قوتابخانەی قەریتاغی بنەڕەتی تێکەڵاو لە شاری هەولێر', NULL, 'completed', NULL, NULL, '2026-05-25T19:28:36.708Z', '2026-05-25T19:28:36.709Z') ON CONFLICT DO NOTHING;
INSERT INTO projects (title, description, category, status, image_url, location, created_at, updated_at) VALUES ('Medical Supply Distribution', 'Distributed essential medical supplies to hospitals and health centers in Erbil', NULL, 'completed', NULL, NULL, '2026-05-25T19:28:36.715Z', '2026-05-25T19:28:36.716Z') ON CONFLICT DO NOTHING;
