// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wahuoitatqcsurjvoqff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhaHVvaXRhdHFjc3VyanZvcWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTYzNDksImV4cCI6MjA2NTQ5MjM0OX0.HkSG2ptTxU8eijR_uQ-u47_caS3B9PpLYf4a2TAqED8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);