// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbugbgwrzfznbsklteje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtidWdiZ3dyemZ6bmJza2x0ZWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjE0MjUsImV4cCI6MjA1Nzk5NzQyNX0.LIIoymSOPBPzrgnCumlPk9p4yyL7WeiyLqHjmZSg1VI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);